name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    name: Build and Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Verify server files
      run: |
        echo "Checking backend files..."
        test -f "server.js" && echo "✅ server.js exists"
        test -f "package.json" && echo "✅ package.json exists"
    
    - name: Validate server.js syntax
      run: |
        echo "Validating server.js syntax..."
        node --check server.js
        echo "✅ No syntax errors in server.js!"
    
    - name: Build status
      run: echo "🎉 Backend validation completed successfully!"